/**
 * Generate a migration from the diff between the entities and a PostgreSQL
 * database (gateway pattern).
 *
 *   pnpm migration:generate --name=AddFoo [--url=postgres://…]
 *
 * Flow (mirrors `typeorm migration:generate`, but programmatic — the CLI's own
 * TS loader chokes on legacy decorators under Node 24):
 *   1. bring the target DB up to date (same path as server boot),
 *   2. diff the entity metadata against it via SchemaBuilder.log(),
 *   3. write server/migrations/<timestamp>-<Name>.ts with up()/down() SQL,
 *   4. remind you to register the class in server/migrations/index.ts.
 *
 * Exit code 1 when there is nothing to generate (useful in CI).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

function resolveUrl(): string {
  const arg = process.argv.find((a) => a.startsWith("--url="));
  if (arg) return arg.slice(6);
  return (
    process.env.DATABASE_URL ||
    "postgres://invoicer:invoicer@localhost:5432/invoicer"
  );
}

function resolveName(): string {
  const arg = process.argv.find((a) => a.startsWith("--name="));
  const raw = arg ? arg.slice(7) : process.env.MIGRATION_NAME;
  if (!raw) {
    console.error("[migration:generate] --name=<PascalCaseName> is required");
    process.exit(1);
  }
  if (!/^[A-Z][A-Za-z0-9]*$/.test(raw)) {
    console.error(
      "[migration:generate] name must be PascalCase (e.g. AddUserAvatar)",
    );
    process.exit(1);
  }
  return raw;
}

const url = resolveUrl();
const name = resolveName();
process.env.DATABASE_URL = url;

// 1. Bring the target database fully up to date so the diff starts from latest.
const { initDataSource, closeDataSource } =
  await import("../server/utils/database");
try {
  await initDataSource();
} finally {
  await closeDataSource();
}

// 2. Diff entity metadata against the (now current) schema.
const { AppDataSource } = await import("../server/utils/database");
try {
  await AppDataSource.initialize();
  const { upQueries, downQueries } = await AppDataSource.driver
    .createSchemaBuilder()
    .log();
  if (upQueries.length === 0) {
    console.log("[migration:generate] no schema changes detected");
    process.exit(1);
  }

  const timestamp = Date.now();
  const className = `${name}${timestamp}`;
  const file = resolve("server/migrations", `${timestamp}-${name}.ts`);

  const render = (queries: { query: string }[]): string =>
    queries
      .map((q) => `  ${JSON.stringify(q.query.replace(/\s+/g, " ").trim())},`)
      .join("\n");

  const content = `import { type MigrationInterface, type QueryRunner } from "typeorm";

/**
 * Generated by \`pnpm migration:generate --name=${name}\` — diff of the entities
 * against ${url.replace(/:[^:@/]+@/, ":***@")}. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand if needed).
 */
export class ${className} implements MigrationInterface {
  name = "${className}";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
${render(upQueries)}
]

const DOWN: string[] = [
${render(downQueries)}
]
`;
  writeFileSync(file, content);
  console.log(
    `[migration:generate] wrote ${file} (${upQueries.length} up / ${downQueries.length} down)`,
  );
  console.log(
    "[migration:generate] NEXT: register the class in server/migrations/index.ts",
  );
} finally {
  if (AppDataSource.isInitialized) await AppDataSource.destroy();
}
