import { type MigrationInterface, type QueryRunner } from "typeorm";

/**
 * Generated by `pnpm migration:generate --name=Init` — diff of the entities
 * against postgres://invoicer:***@localhost:15432/invoicer. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand if needed).
 */
export class Init1788094800471 implements MigrationInterface {
  name = "Init1788094800471";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
  // ── better-auth core + organization plugin tables — NOT TypeORM entities,
  // so the generator never sees them; hand-frozen here with better-auth's own
  // quoted camelCase identifiers (byte-stable with what better-auth queries).
  'CREATE TABLE "user" ("id" text NOT NULL PRIMARY KEY, "name" text NOT NULL, "email" text NOT NULL UNIQUE, "emailVerified" boolean NOT NULL DEFAULT false, "image" text, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL)',
  'CREATE TABLE "session" ("id" text NOT NULL PRIMARY KEY, "expiresAt" TIMESTAMP NOT NULL, "token" text NOT NULL UNIQUE, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL, "ipAddress" text, "userAgent" text, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "activeOrganizationId" text)',
  'CREATE TABLE "account" ("id" text NOT NULL PRIMARY KEY, "accountId" text NOT NULL, "providerId" text NOT NULL, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" TIMESTAMP, "refreshTokenExpiresAt" TIMESTAMP, "scope" text, "password" text, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL)',
  'CREATE TABLE "verification" ("id" text NOT NULL PRIMARY KEY, "identifier" text NOT NULL, "value" text NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NOT NULL)',
  'CREATE TABLE "organization" ("id" text NOT NULL PRIMARY KEY, "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "logo" text, "createdAt" TIMESTAMP NOT NULL, "metadata" text)',
  'CREATE TABLE "member" ("id" text NOT NULL PRIMARY KEY, "organizationId" text NOT NULL REFERENCES "organization"("id") ON DELETE CASCADE, "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "role" text NOT NULL, "createdAt" TIMESTAMP NOT NULL)',
  'CREATE TABLE "invitation" ("id" text NOT NULL PRIMARY KEY, "organizationId" text NOT NULL REFERENCES "organization"("id") ON DELETE CASCADE, "email" text NOT NULL, "role" text, "status" text NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL, "inviterId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE)',
  'CREATE TABLE "campaigns" ("id" SERIAL NOT NULL, "user_id" text NOT NULL, "organization_id" text, "name" text NOT NULL DEFAULT \'\', "expected_title" text NOT NULL, "expected_tax_id" text, "visibility" text NOT NULL DEFAULT \'internal\', "searchable" boolean NOT NULL DEFAULT false, "status" text NOT NULL DEFAULT \'active\', "deadline" TIMESTAMP, "visibility_confirmed" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_campaigns" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_campaigns_org" ON "campaigns" ("organization_id")',
  'CREATE INDEX "idx_campaigns_user" ON "campaigns" ("user_id")',
  'CREATE TABLE "campaign_collaborators" ("id" SERIAL NOT NULL, "campaign_id" integer NOT NULL, "user_id" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_campaign_collaborators" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_campaign_collaborators_user" ON "campaign_collaborators" ("user_id")',
  'CREATE UNIQUE INDEX "uq_campaign_collaborators" ON "campaign_collaborators" ("campaign_id", "user_id")',
  'CREATE TABLE "invoices" ("id" SERIAL NOT NULL, "campaign_id" integer NOT NULL, "uploader_id" text, "group_id" integer, "kind" text NOT NULL DEFAULT \'invoice\', "extracted_merchant" text, "extracted_order_no" text, "filename" text NOT NULL, "saved_path" text NOT NULL, "file_type" text NOT NULL, "status" text NOT NULL DEFAULT \'pending\', "review_state" text NOT NULL DEFAULT \'draft\', "reason" text, "extracted_title" text, "extracted_tax_id" text, "extracted_amount" double precision, "manual_amount" double precision, "amount_in_total" boolean NOT NULL DEFAULT false, "raw_text" text, "error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "processed_at" TIMESTAMP, CONSTRAINT "pk_invoices" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_invoices_uploader" ON "invoices" ("uploader_id")',
  'CREATE INDEX "idx_invoices_status" ON "invoices" ("status")',
  'CREATE INDEX "idx_invoices_campaign" ON "invoices" ("campaign_id")',
  'CREATE TABLE "mail_configs" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "smtp_server" text NOT NULL DEFAULT \'\', "smtp_port" integer NOT NULL DEFAULT \'465\', "use_ssl" boolean NOT NULL DEFAULT true, "use_tls" boolean NOT NULL DEFAULT false, "use_password" boolean NOT NULL DEFAULT true, "sender_email" text NOT NULL DEFAULT \'\', "sender_email_display" text NOT NULL DEFAULT \'\', "sender_domain" text NOT NULL DEFAULT \'\', "sender_password" text NOT NULL DEFAULT \'\', "max_len_recipient_email" integer NOT NULL DEFAULT \'64\', "max_len_subject" integer NOT NULL DEFAULT \'255\', "max_len_body" integer NOT NULL DEFAULT \'50000\', "provider" text NOT NULL DEFAULT \'smtp\', "post_url" text NOT NULL DEFAULT \'\', "post_schema" text NOT NULL DEFAULT \'smtogo\', "post_auth_token" text NOT NULL DEFAULT \'\', "post_field_map" text NOT NULL DEFAULT \'\', "post_schemas" text NOT NULL DEFAULT \'\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_mail_configs" PRIMARY KEY ("id"))',
  'CREATE UNIQUE INDEX "uq_mail_configs_user" ON "mail_configs" ("user_id")',
  'CREATE TABLE "app_settings" ("key" text NOT NULL, "value" text NOT NULL DEFAULT \'{}\', CONSTRAINT "pk_app_settings" PRIMARY KEY ("key"))',
  'CREATE TABLE "org_settings" ("id" SERIAL NOT NULL, "organization_id" text NOT NULL, "visibility" text NOT NULL DEFAULT \'public\', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_org_settings" PRIMARY KEY ("id"))',
  'CREATE UNIQUE INDEX "uq_org_settings_org" ON "org_settings" ("organization_id")',
  'CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "organization_id" text, "campaign_id" integer, "actor_id" text NOT NULL, "action" text NOT NULL, "target" text NOT NULL DEFAULT \'\', "meta" text NOT NULL DEFAULT \'{}\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_audit_logs" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_audit_logs_created" ON "audit_logs" ("created_at")',
  'CREATE INDEX "idx_audit_logs_org" ON "audit_logs" ("organization_id")',
  'CREATE INDEX "idx_audit_logs_campaign" ON "audit_logs" ("campaign_id")',
  'CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" text NOT NULL, "type" text NOT NULL, "link" text NOT NULL DEFAULT \'\', "data" text NOT NULL DEFAULT \'{}\', "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_notifications" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_notifications_user" ON "notifications" ("user_id", "read_at")',
  'CREATE TABLE "campaign_transfers" ("id" SERIAL NOT NULL, "campaign_id" integer NOT NULL, "from_organization_id" text NOT NULL, "to_organization_id" text NOT NULL, "requested_by" text NOT NULL, "status" text NOT NULL DEFAULT \'pending\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_campaign_transfers" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_campaign_transfers_to" ON "campaign_transfers" ("to_organization_id")',
  'CREATE INDEX "idx_campaign_transfers_campaign" ON "campaign_transfers" ("campaign_id")',
  'CREATE TABLE "org_custom_roles" ("id" SERIAL NOT NULL, "organization_id" text NOT NULL, "name" text NOT NULL, "base_role" text NOT NULL, "permissions" text NOT NULL DEFAULT \'[]\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_org_custom_roles" PRIMARY KEY ("id"))',
  'CREATE UNIQUE INDEX "uq_org_custom_roles" ON "org_custom_roles" ("organization_id", "name")',
  'CREATE TABLE "user_emails" ("id" SERIAL NOT NULL, "user_id" text NOT NULL, "email" text NOT NULL, "verified_at" TIMESTAMP, "token_hash" text, "token_expires_at" TIMESTAMP, "code_hash" text, "code_expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_user_emails" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_user_emails_user" ON "user_emails" ("user_id")',
  'CREATE UNIQUE INDEX "uq_user_emails_email" ON "user_emails" ("email")',
  'CREATE TABLE "site_admins" ("user_id" text NOT NULL, "source" text NOT NULL DEFAULT \'granted\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90b33efa93211059c7d06d6e88f" PRIMARY KEY ("user_id"))',
  'CREATE TABLE "passkeys" ("id" SERIAL NOT NULL, "credential_id" text NOT NULL, "user_id" text NOT NULL, "public_key" bytea NOT NULL, "counter" integer NOT NULL DEFAULT \'0\', "transports" text, "device_type" text, "backed_up" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_passkeys" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_passkeys_user" ON "passkeys" ("user_id")',
  'CREATE UNIQUE INDEX "uq_passkeys_credential_id" ON "passkeys" ("credential_id")',
  'CREATE TABLE "campaign_groups" ("id" SERIAL NOT NULL, "campaign_id" integer NOT NULL, "name" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_campaign_groups" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_campaign_groups_campaign" ON "campaign_groups" ("campaign_id")',
  'CREATE UNIQUE INDEX "uq_campaign_groups_name" ON "campaign_groups" ("campaign_id", "name")',
  'CREATE TABLE "group_reviewers" ("id" SERIAL NOT NULL, "group_id" integer NOT NULL, "user_id" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_group_reviewers" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_group_reviewers_user" ON "group_reviewers" ("user_id")',
  'CREATE UNIQUE INDEX "uq_group_reviewers" ON "group_reviewers" ("group_id", "user_id")',
  'CREATE TABLE "invoice_titles" ("id" SERIAL NOT NULL, "owner_type" text NOT NULL, "owner_id" text NOT NULL DEFAULT \'\', "title" text NOT NULL, "tax_id" text NOT NULL DEFAULT \'\', "bank_name" text NOT NULL DEFAULT \'\', "bank_account" text NOT NULL DEFAULT \'\', "address" text NOT NULL DEFAULT \'\', "phone" text NOT NULL DEFAULT \'\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_invoice_titles" PRIMARY KEY ("id"))',
  'CREATE INDEX "idx_invoice_titles_owner" ON "invoice_titles" ("owner_type", "owner_id")',
  'CREATE TABLE "campaign_titles" ("id" SERIAL NOT NULL, "campaign_id" integer NOT NULL, "title_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_campaign_titles" PRIMARY KEY ("id"))',
  'CREATE UNIQUE INDEX "uq_campaign_titles" ON "campaign_titles" ("campaign_id", "title_id")',
];

const DOWN: string[] = [
  // better-auth tables (reverse of the hand-frozen block above)
  'DROP TABLE IF EXISTS "invitation"',
  'DROP TABLE IF EXISTS "member"',
  'DROP TABLE IF EXISTS "organization"',
  'DROP TABLE IF EXISTS "verification"',
  'DROP TABLE IF EXISTS "account"',
  'DROP TABLE IF EXISTS "session"',
  'DROP TABLE IF EXISTS "user"',
  'DROP TABLE "campaigns"',
  'DROP INDEX IF EXISTS "public"."idx_campaigns_org"',
  'DROP INDEX IF EXISTS "public"."idx_campaigns_user"',
  'DROP TABLE "campaign_collaborators"',
  'DROP INDEX IF EXISTS "public"."idx_campaign_collaborators_user"',
  'DROP INDEX IF EXISTS "public"."uq_campaign_collaborators"',
  'DROP TABLE "invoices"',
  'DROP INDEX IF EXISTS "public"."idx_invoices_uploader"',
  'DROP INDEX IF EXISTS "public"."idx_invoices_status"',
  'DROP INDEX IF EXISTS "public"."idx_invoices_campaign"',
  'DROP TABLE "mail_configs"',
  'DROP INDEX IF EXISTS "public"."uq_mail_configs_user"',
  'DROP TABLE "app_settings"',
  'DROP TABLE "org_settings"',
  'DROP INDEX IF EXISTS "public"."uq_org_settings_org"',
  'DROP TABLE "audit_logs"',
  'DROP INDEX IF EXISTS "public"."idx_audit_logs_created"',
  'DROP INDEX IF EXISTS "public"."idx_audit_logs_org"',
  'DROP INDEX IF EXISTS "public"."idx_audit_logs_campaign"',
  'DROP TABLE "notifications"',
  'DROP INDEX IF EXISTS "public"."idx_notifications_user"',
  'DROP TABLE "campaign_transfers"',
  'DROP INDEX IF EXISTS "public"."idx_campaign_transfers_to"',
  'DROP INDEX IF EXISTS "public"."idx_campaign_transfers_campaign"',
  'DROP TABLE "org_custom_roles"',
  'DROP INDEX IF EXISTS "public"."uq_org_custom_roles"',
  'DROP TABLE "user_emails"',
  'DROP INDEX IF EXISTS "public"."idx_user_emails_user"',
  'DROP INDEX IF EXISTS "public"."uq_user_emails_email"',
  'DROP TABLE "site_admins"',
  'DROP TABLE "passkeys"',
  'DROP INDEX IF EXISTS "public"."idx_passkeys_user"',
  'DROP INDEX IF EXISTS "public"."uq_passkeys_credential_id"',
  'DROP TABLE "campaign_groups"',
  'DROP INDEX IF EXISTS "public"."idx_campaign_groups_campaign"',
  'DROP INDEX IF EXISTS "public"."uq_campaign_groups_name"',
  'DROP TABLE "group_reviewers"',
  'DROP INDEX IF EXISTS "public"."idx_group_reviewers_user"',
  'DROP INDEX IF EXISTS "public"."uq_group_reviewers"',
  'DROP TABLE "invoice_titles"',
  'DROP INDEX IF EXISTS "public"."idx_invoice_titles_owner"',
  'DROP TABLE "campaign_titles"',
  'DROP INDEX IF EXISTS "public"."uq_campaign_titles"',
];
