/**
 * Migration barrel — the ordered list of migrations, imported explicitly (not
 * globbed) so the Nitro production bundle includes them and the server can
 * auto-apply pending migrations on boot. The `migration:*` CLI scripts reuse
 * this same list through `server/utils/database.ts` (the verifier-gateway
 * pattern). New migrations: `pnpm migration:generate --name=…`, then register
 * the class here.
 *
 * The first entry is special: `BASELINE_MIGRATION` identifies it. Fresh
 * Postgres databases run it in full (entity DDL generated by the diff against
 * an empty database, plus better-auth's own tables hand-frozen inside); there
 * are no pre-migration PG databases — existing SQLite deployments move over
 * with scripts/migrate-sqlite-to-pg.ts (data ETL, not history replay).
 */
import { Init1788094800471 } from "./1788094800471-Init";

/** Identity of the first (baseline) migration. */
export const BASELINE_MIGRATION = {
  timestamp: 1788094800471,
  name: "Init1788094800471",
} as const;

// typeorm typings expect `MixedList<string | Function>` for the DataSource
// option; migration classes satisfy that at runtime (classes are functions)
// but not structurally, hence the cast through unknown.
export const migrations = [Init1788094800471] as unknown as (
  string | (() => unknown)
)[];
